### ISSUE TITLE
Define size limit for order messages accepted by nodes

### ISSUE THREAD

**Issue by L-Kov** [ParadigmFoundation/PIPs#1]
# Summary
This modification will arbitrarily cap the size of order messages. 
# Motivation
Currently orders conforming to the format defined by `paradigm-connect` are considered valid. Without constraint, there exists a potential attack vector. An example "attack" would be the abuse of this loose construct by initializing and submitting an order with an absurd number of elements in the `makerArguments` array.
# Specification
To mitigate this attack vector we can modify the `checkOrder` method in `order.ts` of module `src/abci/handlers`. The proposed modification would be made to the following method, perhaps preceding `poster = order.recoverPoster().toLowerCase();`. The maximum order size is arbitrary, but I suggest **~780,000 bytes** for the `ORDER_SIZE_LIMIT` as this is the Ethereum transaction size limit with the current Ethereum block gas limit.

A suggested implementation of this limit included below within the existing `checkTx()` implementation:
```typescript

export function checkOrder(tx: SignedOrderTx, state: State) {
    let order;  // Paradigm order object
    let poster; // Recovered poster address from signature

    try {
        // Construct order object, and recover poster signature
        order = new Order(tx.data);

        // Constrain order object size here (begin modified code)
        if (Buffer.from(JSON.stringify(order)).length > ORDER_SIZE_LIMIT) {
            throw Error("Order exceeds max size.");
        }
        // End modified code.

        poster = order.recoverPoster().toLowerCase();
    } catch (err) {
        Logger.mempoolWarn(msg.abci.errors.format);
        return Vote.invalid(msg.abci.errors.format);
    }

    if (
        state.limits.hasOwnProperty(poster) &&
        state.limits[poster].orderLimit > 0
    ) {
        Logger.mempool(msg.abci.messages.mempool);
        return Vote.valid(`(unconfirmed) OrderID: ${Hasher.hashOrder(order)}`);
    } else {
        Logger.mempoolWarn(msg.abci.messages.noStake);
        return Vote.invalid(msg.abci.messages.noStake);
    }
}
```
# Notes
`ORDER_SIZE_LIMIT` would be a consensus parameter validator agree upon during network initialization via the `InitChain()` Tendermint function.

**Comment by hrharder** [comment]
Logic implemented in ParadigmCore [`v0.4.1`](https://github.com/ParadigmFoundation/ParadigmCore/pull/22). A maximum order size will be defined as a consensus parameter in PC v0.5.
